CREATE ROLE rails_user WITH LOGIN ENCRYPTED PASSWORD 'password' CREATEDB;
CREATE ROLE oauth_user WITH LOGIN ENCRYPTED PASSWORD 'password' CREATEDB;
CREATE DATABASE rails_development WITH OWNER rails_user ENCODING 'UTF8';
CREATE DATABASE rails_production  WITH OWNER rails_user ENCODING 'UTF8';
CREATE DATABASE rails_test        WITH OWNER rails_user ENCODING 'UTF8';
CREATE DATABASE oauth_development WITH OWNER oauth_user ENCODING 'UTF8';
