source 'http://rubygems.org'

# Server Framework
gem 'rails', '5.0.1'
gem 'pg', '0.19.0'
gem 'passenger', '5.1.2', require: "phusion_passenger/rack_handler"

gem 'responders'

group :production do
  gem 'newrelic_rpm'
  gem 'dalli' # MemCachier store.
end

group :test do
  gem 'simplecov', :require => false
end

# Auditing
gem 'paper_trail'
gem 'deep_cloneable'

# Amazon SQS
gem 'aws-sdk', '>= 2.0'

# CORS - config in application.rb
gem 'rack-cors', require: 'rack/cors'

# Server to Server API (rails-to-oauth)
gem 'rest-client'

# Redis for serving Index.
gem 'redis'

# Slim for Mailer Views
gem 'slim'

# State Machine
gem 'aasm'

# For quickly parsing CSVs into arrays of hashes
gem 'smarter_csv'

# Delayed Job (background processing)
gem 'delayed_job_active_record'

# Discourse API
gem 'discourse_api'

# Tagging gem
gem 'acts-as-taggable-on', '~> 4.0'

# Pagination
gem 'kaminari'

# JSONAPI
gem 'jsonapi', '0.1.1.beta6'
gem 'jsonapi-parser', '0.1.1.beta3'
gem 'jsonapi-renderer', '0.1.1.beta1'

# Thinkspace
gem 'paperclip'
gem 'spreadsheet'
gem 'has_secure_token'
gem 'cancancan', '1.16.0'
